user:
  host: "0.0.0.0"
  port: 8000

db:
  driver: "postgres"
  # host: "127.0.0.1"
  host: "draft-postgres"
  port: "5432"
  user: "postgres"
  name: "postgres"
  password: "password"
  sslMode: "disable"

cacheRedis:
  host: "draft-redis"
  port: "6379"
  password: ""
  dbNumber: 0

twitter:
  api_key: XXXXXXXXXX
  api_key_secret: XXXXXXXXXX
  bearer_token: XXXXXXXXXX
  user_id: XXXXXXXXXX
